### PR TITLE
🚀CI/CD for FE🌐

### PR DESCRIPTION
**Pull request by maifeeulasad**
🚀 **PR: Next.js to GitHub Pages Deployment**🚀

Hey there, Adam! 👋

I'm excited to present this Pull Request, which brings some fantastic enhancements to our Next.js project and sets up seamless deployment to GitHub Pages. 🌐

**Changes Made:**

1. **GitHub Actions Workflow**: I've added a new workflow file `.github/workflows/fe-2-gh-pages.yml`. This workflow runs on every push to the `main` branch. It builds our Next.js app, exports it to static HTML using `npm run export`, and deploys it to GitHub Pages. This means we can now easily share our app with the world! 🚀

2. **Next.js Configuration**: In `frontend/next.config.js`, I made some improvements. First, I set `reactStrictMode` to `true`, ensuring that our application adheres to best practices and catches potential issues during development. Additionally, I've updated the `assetPrefix` to `'/'`, ensuring that our assets load correctly. I also enabled the `unoptimized` option for images, as we won't be using the Image Optimization API for export. 🎨

3. **Package.json Updates**: In `frontend/package.json`, I added the `export` script, making it convenient to generate the static HTML files for deployment. Now we can easily run `npm run export` to create the optimized static site. 📦

These changes enable us to quickly deploy our Next.js application to GitHub Pages and share our amazing work with the world. 🌍

Let's review and merge this PR to unlock the power of easy and automated deployments! 💪

Surely, you need to make some configurations under the Secrets tab. I guess we can work on that together. 🤝

Thank you for your attention, and happy coding! 🚀🔥

Best regards,
Maifee

### CODE REVIEW

**Comment by maifeeulasad** [comment]
My live demo is available at: https://maifeeulasad.github.io/dApp-car-dealership/

**Comment by charmingdata** [comment]
This is really cool, @maifeeulasad . Thank you for making it easier to deploy. I'm excited about the possibility of using GitHub pages. I've never done so, but I've heard a lot about it.

**Comment by maifeeulasad** [comment]
## Steps to setup GH pipeline:
 - Get `ssh-keygen` (should be available already)
 - Run this command `ssh-keygen -t rsa -b 4096`
   - Save it to a nice place (In windows it's saved under `C:\Users\<username>\.ssh\`)
   - If you give the path `C:\Users\<username>\.ssh\test`, it should generate two files for you, one public key (*with `.pub` extension*), another private (*without any extension*)
   -  Backup to some cloud store and remove it from local storage
 - Go to *secrets* under *settings*
   - For this repo, I went to: https://github.com/charmingdata/dApp-car-dealership/settings/secrets/actions
   - Open the private key, *file WITHOUT `.pub` extension*, with any text editor or in terminal
   -  Paste it write there
   - Name it `ACTIONS_DEPLOY_KEY`
 - Go to *deploy keys* under *settings*
   - For this repo: https://github.com/charmingdata/dApp-car-dealership/settings/keys
   - Open the public key and paste there
   - Give it write access(must)
   - Name it `public ACTIONS_DEPLOY_KEY`
 - Re-trigger the job / just push a new commit, the job will run

**Comment by charmingdata** [comment]
hi @maifeeulasad I followed the helpful instructions you wrote above for github pages deployment. I was able to [get the repo to deploy](https://charmingdata.github.io/dApp-car-dealership/), however, I think it's "deploying the Readme" because I just see the repo title to display. Do I need to change anything in the Settings--> Pages tab?

image

**Comment by charmingdata** [comment]
image

**Comment by maifeeulasad** [comment]
Sorry @charmingdata that you need to go through it now.

I looked into the logs:
image

I think, it's most probably:
 - you missed to give it write access, or I forgot to tell you that
 - somehow there is some mismatch during paste

**Pull request merged**
